### ISSUE TITLE
Microsoft.Azure.Services.AppAuthentication reference should be removed

### ISSUE THREAD

**Issue by agowdamsft** [Azure-Samples/app-service-managed-identity-key-vault-csharp#1]
The project has reference to NuGet: Microsoft.Azure.Services.AppAuthentication but I dont see it being used in any classes. Better to remove

**Comment by bartr** [comment]
We are working on a PR and will include this fix. Thanks for the feedback.

**Comment by bartr** [comment]
Resolved with PR 1
